# Generated by Django 5.0.2 on 2025-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appLigas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deporte',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
    ]
